# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SmartCycle.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SmartCycle.proto\"\xb3\x02\n\tTelemetry\x12\r\n\x05speed\x18\x01 \x01(\x02\x12\x0f\n\x07\x63\x61\x64\x65nce\x18\x02 \x01(\x02\x12\x13\n\x0btarget_gear\x18\x03 \x01(\x05\x12\x14\n\x0c\x63urrent_gear\x18\x04 \x01(\x05\x12\x1f\n\x05state\x18\x05 \x01(\x0e\x32\x10.Telemetry.State\x12/\n\x0fup_shift_button\x18\x06 \x01(\x0e\x32\x16.Telemetry.ButtonState\x12\x31\n\x11\x64own_shift_button\x18\x07 \x01(\x0e\x32\x16.Telemetry.ButtonState\",\n\x05State\x12\n\n\x06\x42IKING\x10\x00\x12\x0b\n\x07STOPPED\x10\x01\x12\n\n\x06\x41SLEEP\x10\x02\"(\n\x0b\x42uttonState\x12\x0c\n\x08RELEASED\x10\x00\x12\x0b\n\x07PRESSED\x10\x01\"\xa7\x02\n\x06Tuning\x12$\n\x1cnominal_gear_encoder_value_1\x18\x01 \x01(\x03\x12$\n\x1cnominal_gear_encoder_value_2\x18\x02 \x01(\x03\x12$\n\x1cnominal_gear_encoder_value_3\x18\x03 \x01(\x03\x12$\n\x1cnominal_gear_encoder_value_4\x18\x04 \x01(\x03\x12$\n\x1cnominal_gear_encoder_value_5\x18\x05 \x01(\x03\x12$\n\x1cnominal_gear_encoder_value_6\x18\x06 \x01(\x03\x12\x1c\n\x14\x64\x65sired_cadence_high\x18\x07 \x01(\r\x12\x1b\n\x13\x64\x65sired_cadence_low\x18\x08 \x01(\r\"O\n\x07Message\x12\x1f\n\ttelemetry\x18\x01 \x01(\x0b\x32\n.TelemetryH\x00\x12\x19\n\x06tuning\x18\x02 \x01(\x0b\x32\x07.TuningH\x00\x42\x08\n\x06packetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SmartCycle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRY']._serialized_start=21
  _globals['_TELEMETRY']._serialized_end=328
  _globals['_TELEMETRY_STATE']._serialized_start=242
  _globals['_TELEMETRY_STATE']._serialized_end=286
  _globals['_TELEMETRY_BUTTONSTATE']._serialized_start=288
  _globals['_TELEMETRY_BUTTONSTATE']._serialized_end=328
  _globals['_TUNING']._serialized_start=331
  _globals['_TUNING']._serialized_end=626
  _globals['_MESSAGE']._serialized_start=628
  _globals['_MESSAGE']._serialized_end=707
# @@protoc_insertion_point(module_scope)
